// Auto-generated from docs/wisor/Charge codes_CW(1)_UPDATED.xlsx
// 107 canonical Braiin charge codes mapped from Cargowise dictionary.
// Every entry has tmsOrigin='cargowise' - matches migration 040 seed.

export type TmsOrigin = 'cargowise' | 'magaya' | 'descartes' | 'native';

export interface ChargeCode {
  braiinCode: string;
  description: string;
  billingType: 'margin' | 'revenue' | 'disbursement';
  macroGroup: 'origin_exw' | 'freight' | 'destination_delivery' | 'insurance_other';
  defaultMarginPct: number;
  applicableModes: string[];
  applicableDirections: string[];
  tmsOrigin: TmsOrigin;
  cwCode: string;
  cwDepartments: string[];
}

export const CHARGE_CODES: ChargeCode[] = [
  {
    braiinCode: "administration_fee",
    description: "ADMINISTRATION FEE",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "ADMIN",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "agency_fee",
    description: "AGENCY FEE",
    billingType: "revenue",
    macroGroup: "insurance_other",
    defaultMarginPct: 0.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "AGEFEE",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "air_freight",
    description: "Air Freight",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["air"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "AFRT",
    cwDepartments: ["FEA", "FIA", "CEA", "CIA"],
  },
  {
    braiinCode: "airline_collection",
    description: "Airline Collection",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "ACOL",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "airline_delivery",
    description: "Airline Delivery",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "ADEL",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "airline_handling",
    description: "Airline Handling",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "AHAN",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "amendment_fee",
    description: "Amendment fee",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "AMEND",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "ams_aci_fee",
    description: "AMS/ACI FEE",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "AMS",
    cwDepartments: ["FES", "FIS", "CES", "CIS", "FIA", "FEA"],
  },
  {
    braiinCode: "bank_service_charge",
    description: "Bank service charge",
    billingType: "revenue",
    macroGroup: "insurance_other",
    defaultMarginPct: 0.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "BANK",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "booking_fee",
    description: "Booking Fee",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "BOOK",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "bunker_adjustment_factor",
    description: "Bunker Adjustment Factor",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "BAF",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "cancellation_fee_wasted_journey",
    description: "Cancellation Fee / Wasted Journey",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "CFEE",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "cleaning_fee",
    description: "Cleaning Fee",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl"],
    applicableDirections: ["import"],
    tmsOrigin: 'cargowise',
    cwCode: "CLEAN",
    cwDepartments: ["FIS", "CIS"],
  },
  {
    braiinCode: "collection",
    description: "Collection",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "COLL",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "co_loader_costs",
    description: "Co-Loader Costs",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "COLOAD",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "container_devan",
    description: "Container Devan",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DEVAN",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "container_inspection_fee",
    description: "Container Inspection Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "INSPEC",
    cwDepartments: ["FEA", "FIA", "FIS", "FES"],
  },
  {
    braiinCode: "container_protect_essential",
    description: "Container Protect Essential",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "CP1",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "container_shunt",
    description: "Container Shunt",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "SHUNT",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "continuous_bond_fee",
    description: "Continuous Bond Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "CONBON",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "currency_adjustment_factor",
    description: "Currency Adjustment Factor",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "CAF",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "currency_exposure_fee",
    description: "Currency Exposure Fee",
    billingType: "revenue",
    macroGroup: "insurance_other",
    defaultMarginPct: 0.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "CURR",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "customs_port_costs_origin",
    description: "Customs Port Costs - Origin",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "CPCO",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "delivery",
    description: "Delivery",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DEL",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "delivery_order_fee",
    description: "Delivery Order Fee",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 0.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "DOF",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "demurrage",
    description: "Demurrage",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "CDEM",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "destination_other_charges",
    description: "Destination - Other Charges",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DNOTE",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "destination_airline_handling",
    description: "Destination Airline Handling",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DAHAN",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "destination_coordination_services",
    description: "Destination Coordination Services",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DCS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "destination_documentation_fee",
    description: "Destination Documentation Fee",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 0.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "DDOC",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "destination_miscellaneous_charges",
    description: "Destination Miscellaneous Charges",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "DSTM",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "destination_storage_warehousing",
    description: "Destination Storage / Warehousing",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "DSTOR",
    cwDepartments: ["FEA", "FIA", "FES", "FIS"],
  },
  {
    braiinCode: "destination_terminal_handling_charges",
    description: "Destination Terminal Handling Charges",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "DTHC",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "detention",
    description: "Detention",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DETN",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "dg_documentation_fee",
    description: "DG Documentation Fee",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 0.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "DGDOC",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "disbursement_processing_fee_min_gbp_25_or_3_of_duty_vat_payable",
    description: "Disbursement Processing Fee - (Min GBP 25 or 3% of Duty & VAT payable)",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 0.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DEFER",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "discount",
    description: "Discount",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DISC",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "domestic_courier",
    description: "Domestic Courier",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "road", "sea_fcl", "warehouse"],
    applicableDirections: ["domestic", "export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "DCOU",
    cwDepartments: ["FDA", "FEA", "FIA", "FIS", "FES", "FDR", "WFS"],
  },
  {
    braiinCode: "driver_retention_surcharge",
    description: "Driver Retention Surcharge",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DRS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "drop_fee",
    description: "Drop Fee",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DROP",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "duties_and_fees",
    description: "DUTIES AND FEES",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DUT/FEE",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "duty_customs",
    description: "Duty (Customs)",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "DUTY",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "e_manifest",
    description: "E-Manifest",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "EMAN",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "emcs_entry",
    description: "EMCS Entry",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "EMCS",
    cwDepartments: ["FES", "FIS", "CES", "CIS", "FIA", "FEA"],
  },
  {
    braiinCode: "emergency_contingency_surcharge",
    description: "Emergency Contingency Surcharge",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "ECS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "emergency_fuel_adjustment_factor",
    description: "Emergency Fuel Adjustment Factor",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "EFAF",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "emergency_risk_surcharge",
    description: "Emergency Risk Surcharge",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "ERS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "emission_control_areas",
    description: "Emission Control Areas",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "ECA",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "emission_surcharge",
    description: "Emission Surcharge",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "EMS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "ens_fee",
    description: "ENS FEE",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "ENS",
    cwDepartments: ["FES", "FIS", "CES", "CIS", "FIA", "FEA"],
  },
  {
    braiinCode: "entry_prep",
    description: "Entry Prep",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "ENTP",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "equipment_positioning_service_export_cy",
    description: "Equipment Positioning Service Export (CY)",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "EPSE",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "export_customs_clearance_fee",
    description: "Export Customs Clearance Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 0.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "ECCLR",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "exw_charges",
    description: "EXW Charges",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "EXWCH",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "fossil_fuel_fee",
    description: "Fossil Fuel Fee",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "FFF",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "free_in_service",
    description: "Free In Service",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "FRI",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "fuel_surcharge",
    description: "Fuel Surcharge",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "FSC",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "handling_fee",
    description: "Handling Fee",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "HAND",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "hazardous_fee",
    description: "Hazardous Fee",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "AHAZ",
    cwDepartments: ["FEA", "FIA", "FES", "FIS"],
  },
  {
    braiinCode: "imo_surcharge",
    description: "IMO Surcharge",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl"],
    applicableDirections: ["domestic", "export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "IMOSUR",
    cwDepartments: ["FIS", "FES", "FDS"],
  },
  {
    braiinCode: "import_customs_clearance_fee",
    description: "Import Customs Clearance Fee",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 0.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "ICCLR",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "importer_of_record",
    description: "Importer of Record",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "IMPR",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "international_courier",
    description: "International Courier",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "COU",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "isf_filing",
    description: "ISF Filing",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 0.0,
    applicableModes: ["sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "ISF",
    cwDepartments: ["FES", "FIS", "CES", "CIS"],
  },
  {
    braiinCode: "isps",
    description: "ISPS",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "ISPS",
    cwDepartments: ["FES", "FIS", "CES", "CIS"],
  },
  {
    braiinCode: "labelling_fee",
    description: "Labelling Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "LABEL",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "lo_lo",
    description: "LO/LO",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "LOLO",
    cwDepartments: ["FEA", "FIA", "FES", "FIS"],
  },
  {
    braiinCode: "low_sulpher_surcharge_lss",
    description: "Low Sulpher Surcharge (LSS)",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "LSS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "marine_insurance",
    description: "Marine Insurance",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "road", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "INSUR",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS", "FER"],
  },
  {
    braiinCode: "marine_insurance_admin_fee",
    description: "Marine Insurance Admin Fee",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "road", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "INSURAD",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS", "FER"],
  },
  {
    braiinCode: "ocean_freight",
    description: "Ocean Freight",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "OFRT",
    cwDepartments: ["FES", "FIS", "CES", "CIS"],
  },
  {
    braiinCode: "origin_other_charges",
    description: "Origin - Other Charges",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "ONOTE",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "origin_documentation_fee",
    description: "Origin Documentation Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "ODOC",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "origin_storage_warehousing",
    description: "Origin Storage / Warehousing",
    billingType: "disbursement",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "OSTOR",
    cwDepartments: ["FEA", "FIA", "FES", "FIS"],
  },
  {
    braiinCode: "origin_terminal_handling",
    description: "Origin Terminal Handling",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "OTHC",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "packaging",
    description: "Packaging",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["warehouse"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PACKAGE",
    cwDepartments: ["WFS"],
  },
  {
    braiinCode: "pallet_in_fee",
    description: "Pallet in fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PLTIN",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "pallet_out_fee",
    description: "Pallet out fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PLTOT",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "palletising_fee",
    description: "Palletising Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PALLET",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "peak_season_surcharge",
    description: "Peak Season Surcharge",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PSS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "pga_fee",
    description: "PGA Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "PGAF",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "pier_pass_fee",
    description: "Pier Pass Fee",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "PIER",
    cwDepartments: ["FES", "FIS", "CES", "CIS", "FIA", "FEA"],
  },
  {
    braiinCode: "port_additionals_port_dues_import",
    description: "Port Additionals / Port Dues Import",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PAI",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "port_congestion",
    description: "Port Congestion",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "CONGEST",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "pre_pull",
    description: "Pre-Pull",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PREPUL",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "primary_screening",
    description: "Primary Screening",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PSCR",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "profit_share_rebate",
    description: "Profit Share / Rebate",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "PS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "quay_rent_container_storage",
    description: "Quay Rent / Container Storage",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "QRENT",
    cwDepartments: ["FEA", "FIA", "FES", "FIS"],
  },
  {
    braiinCode: "rail_freight",
    description: "Rail Freight",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "RAIL",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "road_freight",
    description: "Road Freight",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["road"],
    applicableDirections: ["domestic", "export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "RFRT",
    cwDepartments: ["FIR", "FER", "FDR"],
  },
  {
    braiinCode: "secondary_screening",
    description: "Secondary Screening",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "SSCR",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "single_bond_fee",
    description: "Single Bond Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "SINBON",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "special_equipment_fee",
    description: "Special Equipment fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "OSPEC",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "stop_off_fee",
    description: "Stop Off Fee",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "STOFF",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "storage",
    description: "Storage",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "WSTG",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "tail_lift_delivery",
    description: "Tail-lift Delivery",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "TAIL",
    cwDepartments: ["FEA", "FIA", "FES", "FIS", "CEA", "CIA", "CES", "CIS"],
  },
  {
    braiinCode: "transit_disruption_surcharge",
    description: "Transit Disruption Surcharge",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "TDS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "value_protect_starter",
    description: "Value Protect Starter",
    billingType: "margin",
    macroGroup: "insurance_other",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "VPS",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "vat_customs",
    description: "VAT (Customs)",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "VAT",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "vgm_fee",
    description: "VGM Fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "VGM",
    cwDepartments: ["FEA", "FIA", "FES", "FIS"],
  },
  {
    braiinCode: "waiting_time",
    description: "Waiting Time",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "WAIT",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "war_risk_surcharge",
    description: "War Risk Surcharge",
    billingType: "margin",
    macroGroup: "freight",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "WAR",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "warehouse_handling_in",
    description: "Warehouse Handling In",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "WHIN",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "warehouse_handling_out",
    description: "Warehouse Handling Out",
    billingType: "margin",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "WHOUT",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "warehouse_re_work",
    description: "Warehouse Re-work",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "WRWRK",
    cwDepartments: ["ALL"],
  },
  {
    braiinCode: "x_ray_fee",
    description: "X-RAY fee",
    billingType: "margin",
    macroGroup: "origin_exw",
    defaultMarginPct: 100.0,
    applicableModes: ["air", "sea_fcl"],
    applicableDirections: ["export", "import"],
    tmsOrigin: 'cargowise',
    cwCode: "XRAY",
    cwDepartments: ["FEA", "FIA", "FIS", "FES"],
  },
  {
    braiinCode: "yard_storage",
    description: "Yard Storage",
    billingType: "disbursement",
    macroGroup: "destination_delivery",
    defaultMarginPct: 100.0,
    applicableModes: ["sea_fcl", "sea_lcl", "air", "road", "rail"],
    applicableDirections: ["import", "export", "crosstrade"],
    tmsOrigin: 'cargowise',
    cwCode: "YSTG",
    cwDepartments: ["ALL"],
  },
];
