export interface EnrichedAccount {
  company_id: number;
  company_name: string;
  company_domain: string;
  postcode: string;
  trade_type: string;
  status: string;
  icp_score: number;
  icp_grade: string;
  logo_url: string;
  is_forwarder: boolean;
  contact_name: string;
  contact_title: string;
  contact_email: string;
  contact_linkedin: string;
  commodity_summary: string;
  supply_chain_profile: string;
  vertical: string;
  angle: string;
  pain_points: string[];
  email_subject: string;
  email_body_1: string;
  linkedin_connection_note: string;
  linkedin_dm: string;
  ultimate_score: number;
  grade: string;
  import_score: number;
  export_score: number;
  import_months: number;
  export_months: number;
  import_volume: number;
  export_volume: number;
  is_dual: boolean;
  manchester_proximity: boolean;
  company_news: string;
  current_provider: string;
  provider_confidence: "confirmed" | "likely" | "unknown";
  provider_source: string;
  suggested_approach: "rate-led" | "service-led" | "relationship-led" | "expertise-led" | "";
  approach_hook: string;
  researched_at: string;
}
