-- Seed voice_rules from docs/voice/anti-ai-writing-style.md.
--
-- This file is the initial population. The markdown file remains as a
-- design contract / human-readable doc. The dashboard at /dev/voice is
-- the runtime source of truth from here on.
--
-- Adding rules: insert via the dashboard or extend this file in a new
-- migration. Do not edit this file after deploy.

-- =============================================================================
-- Banned words (general AI/LinkedIn cringe)
-- =============================================================================
INSERT INTO voice_rules (rule_type, pattern, replacement, severity, channel, notes) VALUES
  ('banned_word','leverage','use, lean on, or just say what you do with it','block','all','LinkedIn signature word'),
  ('banned_word','unlock','open up, enable, or name what is being made possible','block','all','LinkedIn / corporate cringe'),
  ('banned_word','game-changer','name the specific change with evidence','block','all','Empty hype'),
  ('banned_word','seamlessly','smoothly, or describe what does not break','block','all','LinkedIn cringe'),
  ('banned_word','dive in','get started, or just begin','block','all','Performative'),
  ('banned_word','delve','look at, examine, or just describe what you are doing','block','all','AI tell - common ChatGPT word'),
  ('banned_word','elevate','improve, or name the specific improvement','block','all','Marketing speak'),
  ('banned_word','harness','use, or describe the action directly','block','all','LinkedIn cringe'),
  ('banned_word','robust','tested at X scale, or name the specific failure it survives','block','all','Empty adjective'),
  ('banned_word','synergy','drop, or describe how the two work together','block','all','Peak corporate'),
  ('banned_word','best-in-class','name what makes it best with evidence','block','all','Unsupported superlative'),
  ('banned_word','world-class','drop, or name the actual benchmark met','block','all','Unsupported superlative'),
  ('banned_word','cutting-edge','name the technology or approach','block','all','Empty marketing'),
  ('banned_word','streamline','speed up, cut steps, or name what you removed','block','all','Generic verb'),
  ('banned_word','empower','help, or give them what they need to...','block','all','Empty verb'),
  ('banned_word','navigate','deal with, get through, work through','block','all','Banned only as abstract verb (e.g. "navigate complexity")'),
  ('banned_word','ecosystem','name the actual tools / people / partners','block','all','Empty word'),
  ('banned_word','holistic','looks at the whole picture, or drop','block','all','Buzzword'),
  ('banned_word','actionable','useful, or skip the adjective and name the action','block','all','Empty adjective'),
  ('banned_word','stakeholder','name who: customer, supplier, driver, ops, finance','warn','email','Acceptable in formal contracts; flagged in casual writing'),
  ('banned_word','circle back','follow up, get back to you, or name the day','block','all','Corporate cringe'),
  ('banned_word','touch base','talk, catch up, have a call','block','all','Corporate cringe'),
  ('banned_word','moving forward','drop, or "from now", "next"','block','all','Padding'),
  ('banned_word','going forward','drop, or "from now", "next"','block','all','Padding'),
  ('banned_word','at the end of the day','drop. Get to the point.','block','all','Empty filler'),
  ('banned_word','low-hanging fruit','easy wins, or name the specific opportunity','block','all','Cliche');

-- =============================================================================
-- Banned phrases (freight/logistics specific)
-- =============================================================================
INSERT INTO voice_rules (rule_type, pattern, replacement, severity, channel, notes) VALUES
  ('banned_phrase','end-to-end visibility','what the customer will actually see and when. e.g., "If your box hits a delay in Singapore, you hear about it before your customer does."','block','all','Industry cringe'),
  ('banned_phrase','supply chain optimisation','the named outcome with a number. e.g., "We took 3 days off the Felixstowe -> Sao Paulo lane last quarter."','block','all','Industry cringe'),
  ('banned_phrase','supply chain optimization','the named outcome with a number','block','all','US spelling variant'),
  ('banned_phrase','freight forwarder of the future','drop. Or: "We do not lose shipments."','block','all','Empty positioning'),
  ('banned_phrase','global reach, local expertise','name the lanes and the people. e.g., "Someone in Santos who picks up the phone."','block','all','Industry cringe'),
  ('banned_phrase','global reach and local expertise','name the lanes and the people','block','all','Variant'),
  ('banned_phrase','one-stop shop','name the actual services delivered','block','all','Cliche');

-- =============================================================================
-- Banned tone markers (corporate filler)
-- =============================================================================
INSERT INTO voice_rules (rule_type, pattern, replacement, severity, channel, notes) VALUES
  ('banned_tone','in today''s fast-paced world','drop. Get to the point.','block','all','Generic intro'),
  ('banned_tone','more than ever before','drop. State the current situation.','block','all','Generic intensifier'),
  ('banned_tone','it''s worth noting','if it is worth noting, just note it. Drop the announcement.','block','all','Padding'),
  ('banned_tone','at this moment in time','"now" or "today", or be specific with a date','block','all','Filler'),
  ('banned_tone','going above and beyond','name the specific thing. e.g., "The driver waited four hours at the gate"','block','all','Empty claim'),
  ('banned_tone','we pride ourselves on','show, do not tell. Drop the line, replace with the specific thing','block','all','Corporate cringe'),
  ('banned_tone','as a [role/company type], you understand','do not assume their position. State the situation directly','block','all','Presumptuous opener');

-- =============================================================================
-- Banned tone markers (email openers - the worst offenders)
-- =============================================================================
INSERT INTO voice_rules (rule_type, pattern, replacement, severity, channel, notes) VALUES
  ('banned_tone','I hope this email finds you well','drop. Open with the reason for writing. e.g., "Following up on our chat at the WCA stand..."','block','email','Worst offender'),
  ('banned_tone','I trust this email finds you well','drop. Open with the reason for writing.','block','email','Variant'),
  ('banned_tone','hope you''re keeping well','drop. Specific opener.','block','email','Variant'),
  ('banned_tone','I''m reaching out because','just say what it is about','block','email','Padding'),
  ('banned_tone','just wanted to share','drop the apologetic "just". Send the thing with one line of context.','block','email','Apologetic framing'),
  ('banned_tone','just thought I''d','drop the apologetic "just"','block','email','Apologetic framing'),
  ('banned_tone','just wanted to follow up','drop the "just". "Following up on..." or open with the actual question.','block','email','Apologetic framing'),
  ('banned_tone','just checking in','drop. Either ask the actual question or share the actual update.','block','email','Apologetic framing'),
  ('banned_tone','quick question','just ask the question. If it is quick, it does not need announcing.','block','email','Performative'),
  ('banned_tone','to whom it may concern','research the name. If unknown, address the team / department.','block','email','Lazy salutation');

-- =============================================================================
-- Banned tone markers (email closers / asks)
-- =============================================================================
INSERT INTO voice_rules (rule_type, pattern, replacement, severity, channel, notes) VALUES
  ('banned_tone','looking forward to your response','drop. End with a specific ask: "Can you confirm by Friday?"','block','email','Empty closer'),
  ('banned_tone','please advise','name what you want. "Can you confirm the rate?"','block','email','Abdicates the ask'),
  ('banned_tone','kindly find attached','"see attached" or just attach with one line of context','block','email','Corporate filler'),
  ('banned_tone','kindly do the needful','name the action. Direct ask.','block','email','Corporate filler'),
  ('banned_tone','please find attached','"see attached", or one sentence of context','warn','email','Acceptable but tired - Bruna uses it; preserve when sufficient context surrounds');

-- =============================================================================
-- Banned tone markers (passive-aggressive / performative)
-- =============================================================================
INSERT INTO voice_rules (rule_type, pattern, replacement, severity, channel, notes) VALUES
  ('banned_tone','per my last email','name the topic specifically: "On the rate question from Tuesday..."','block','email','Passive-aggressive'),
  ('banned_tone','friendly reminder','drop the framing. State the thing directly.','block','email','Never lands as friendly'),
  ('banned_tone','as discussed','name what was actually said: "You mentioned the Brazil reefer flow..."','warn','email','Banned only when nothing was actually discussed in detail'),
  ('banned_tone','apologies for the delay','if there was a real delay, name a specific brief reason. Otherwise drop.','warn','email','Performative when no real delay');

-- =============================================================================
-- Banned sentence structures
-- =============================================================================
INSERT INTO voice_rules (rule_type, pattern, replacement, severity, channel, notes) VALUES
  ('banned_structure','not just X but Y','state Y directly. Drop the X comparison unless load-bearing.','block','all','LinkedIn signature move'),
  ('banned_structure','here''s the thing','just say the thing','block','all','Faux-revelation opener'),
  ('banned_structure','here''s what most people miss','open with the specific situation or observation','block','all','Influencer pattern'),
  ('banned_structure','most companies get this wrong','describe what works directly','block','all','Contrarian setup'),
  ('banned_structure','stop X. start Y','describe what works directly. Skip the contrarian framing.','block','all','Influencer pattern'),
  ('banned_structure','three things you need to know','drop the announcement. Lead with the strongest point.','block','all','Listicle smell'),
  ('banned_structure','counterintuitive. but true.','drop. If interesting, it lands on its own.','block','all','Inverted weight opening'),
  ('banned_structure','if you''ve made it this far','be direct: "Want me to send the rate sheet?"','block','all','CTA disguised as humility'),
  ('banned_structure','and that''s how you win','end on the specific, the next step, or a real question','block','all','Empty closing platitude'),
  ('banned_structure','and that''s the difference','same as above','block','all','Empty closing platitude');

-- =============================================================================
-- Banned formatting (universal hard ban)
-- =============================================================================
INSERT INTO voice_rules (rule_type, pattern, replacement, severity, channel, notes) VALUES
  ('banned_formatting','—','use a standard hyphen (-), full stop, or comma','block','all','Em dash banned everywhere - see feedback_hyphens'),
  ('banned_formatting','–','use a standard hyphen (-), full stop, or comma','block','all','En dash banned everywhere');

-- =============================================================================
-- Sanity: confirm seed count for diagnostics
-- =============================================================================
DO $$
DECLARE
  n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n FROM voice_rules;
  RAISE NOTICE 'voice_rules seeded with % rules', n;
END $$;
